import './Introducao.css';

const Intro = () => {
  return (
    <div className="intro-container">
      <div className="intro-content">
        
        <h1 className="intro-title">
          ADSProcSuite
        </h1>
        <h3 className="intro-subtitle">A Processing Environment for ADS (Airborne Digital Sensor) Data</h3>

        <div className="intro-text-container">
          <p className="intro-paragraph">
            The Leica Airborne Digital Sensor (ADS) is widely used in digital aerial survey projects, providing high-resolution imagery for 
            applications in cartography, geoprocessing, and remote sensing (LEICA GEOSYSTEMS, 2014). The large volume of data generated by 
            this system requires specialized tools that combine computational efficiency with methodological rigor.
          </p>
          
          <p className="intro-paragraph">
            In this context, ADSProcSuite, developed at CEPAG, emerges as a solution to optimize workflow, combining low-level C++ algorithms 
            with automation and integration routines in Python.
          </p>
        </div>
        
      </div>
    </div>
  );
};

export default Intro;