import './Introducao.css';

const Intro = () => {
  return (
    <div className="max-h-screen bg-white flex items-center justify-center px-4">
      <div className="max-w-3xl mx-auto text-center">
        
        <h1 className="text-3xl md:text-4xl lg:text-5xl font-light text-gray-900 mb-8 leading-tight">
          ADSProcSuite
        </h1>
        <h3 className="block font-medium text-blue-500 mt-2">A Processing Environment for ADS (Airborne Digital Sensor) Data</h3>

        <div className="space-y-6 text-gray-600 leading-relaxed">
          <p className="text-lg">
            The Leica Airborne Digital Sensor (ADS) is widely used in digital aerial survey projects, providing high-resolution imagery for 
            applications in cartography, geoprocessing, and remote sensing (LEICA GEOSYSTEMS, 2014). The large volume of data generated by 
            this system requires specialized tools that combine computational efficiency with methodological rigor.
          </p>
          
          <p className="text-lg">
            In this context, ADSProcSuite, developed at CEPAG, emerges as a solution to optimize workflow, combining low-level C++ algorithms 
            with automation and integration routines in Python.
          </p>
        </div>
        
      </div>
    </div>
  );
};

export default Intro;