import "./Ferramentas.css";

const Ferramentas = () => {
  const Ferramentas = [
    {
      id: 1,
      title: "Import Data",
      description: "User selects the folder with the files to be checked by the software",
      icon: "-"
    },
    {
      id: 2,
      title: "Check Data",
      description: "Checks the existence of flight files, if they exist, list them on the screen.",
      icon: "-"
    },
    {
      id: 3,
      title: "Flight Map",
      description: "Tonal homogenization between image blocks for visual coherence.",
      icon: "-"
    },
    {
      id: 4,
      title: "Import Log",
      description: "Generates an import log of execution data, indicating success or failure, number of files found and, if not all files were found, lists which ones were not found.",
      icon: "-"
    },
    {
      id: 5,
      title: "Generate Generic DEM",
      description: "Tool to generate generic DE file with low resolution.",
      icon: "-"
    },
    {
      id: 6,
      title: "Fast Orthophoto Generation",
      description: "Tool to quickly generate an orthophoto of one or more flight tracks.",
      icon: "-"
    },
    {
      id: 7,
      title: "Full Orthophoto Generation",
      description: "Tool to generate an orthophoto of one or more flight tracks, with all the customization settings chosen by the user.",
      icon: "-"
    },
    {
      id: 8,
      title: "Orthophoto Equalization",
      description: "	Tool for automatically updating orthophotos using specialized algorithms.",
      icon: "-"
    },
    {
      id: 9,
      title: "Mosaic Preview",
      description: "Tool that generates a visualization of the mosaic generated by low-resolution orthophotos.",
      icon: "-"
    },
    {
      id: 10,
      title: "Ground Point Preview",
      description: "Tool for viewing points in images.",
      icon: "-"
    },
    {
      id: 11,
      title: "Standard DEM Viewer",
      description: "Default program viewer to quickly view the imported DEM file.",
      icon: "-"
    },
    {
      id: 12,
      title: "Advanced DEM Viewer",
      description: "Viewer advancing using QTReader to view the imported DEM file.",
      icon: "-"
    }
  ];

  return (

    <div className="tools-page">
      <div className="Ferramentas-container">
        
        <div className="Ferramentas-content">
          <div className="Ferramentas-header">
            <h2 className="Ferramentas-title">Tools & Features</h2>
            <p className="Ferramentas-subtitle">
              Comprehensive suite of Tools for ADS data processing and analysis
            </p>
          </div>

          <div className="Ferramentas-grid">
            {Ferramentas.map(Ferramenta => (
              <div key={Ferramenta.id} className="Ferramenta-card">
                <div className="Ferramenta-icon">
                  {Ferramenta.icon}
                </div>
                <h3 className="Ferramenta-title">{Ferramenta.title}</h3>
                <p className="Ferramenta-description">{Ferramenta.description}</p>
              </div>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
};

export default Ferramentas;